-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 18:09:20 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 6Bs4988CYl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 6Bs4988CYl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `6Bs4988CYl` DEFAULT CHARACTER SET utf8 ;
USE `6Bs4988CYl` ;

-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`nacionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`nacionalidades` (
  `id_nacionalidades` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_nacionalidades`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`trabalhos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`trabalhos` (
  `id_trabalhos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_trabalhos`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`papeis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`papeis` (
  `id_papeis` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_papeis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`utilizadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`utilizadores` (
  `id_utilizadores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `ref_nacionalidades` INT NOT NULL,
  `ref_trabalhos` INT NOT NULL,
  `ref_papeis` INT NOT NULL,
  `fotografia` VARCHAR(100) NULL,
  PRIMARY KEY (`id_utilizadores`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_utilizadores_nacionalidades_idx` (`ref_nacionalidades` ASC) VISIBLE,
  INDEX `fk_utilizadores_trabalhos1_idx` (`ref_trabalhos` ASC) VISIBLE,
  INDEX `fk_utilizadores_papeis1_idx` (`ref_papeis` ASC) VISIBLE,
  CONSTRAINT `fk_utilizadores_nacionalidades`
    FOREIGN KEY (`ref_nacionalidades`)
    REFERENCES `6Bs4988CYl`.`nacionalidades` (`id_nacionalidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilizadores_trabalhos1`
    FOREIGN KEY (`ref_trabalhos`)
    REFERENCES `6Bs4988CYl`.`trabalhos` (`id_trabalhos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilizadores_papeis1`
    FOREIGN KEY (`ref_papeis`)
    REFERENCES `6Bs4988CYl`.`papeis` (`id_papeis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`icons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`icons` (
  `id_icons` INT NOT NULL AUTO_INCREMENT,
  `ref` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_icons`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`cores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`cores` (
  `id_cores` INT NOT NULL,
  `ref` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`categorias` (
  `id_categorias` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ref_icons` INT NOT NULL,
  `ref_cores` INT NOT NULL,
  PRIMARY KEY (`id_categorias`),
  INDEX `fk_categorias_icons1_idx` (`ref_icons` ASC) VISIBLE,
  INDEX `fk_categorias_cores1_idx` (`ref_cores` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_icons1`
    FOREIGN KEY (`ref_icons`)
    REFERENCES `6Bs4988CYl`.`icons` (`id_icons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorias_cores1`
    FOREIGN KEY (`ref_cores`)
    REFERENCES `6Bs4988CYl`.`cores` (`id_cores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`compras` (
  `id_compras` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `ref_categorias` INT NOT NULL,
  PRIMARY KEY (`id_compras`),
  INDEX `fk_compras_categorias1_idx` (`ref_categorias` ASC) VISIBLE,
  CONSTRAINT `fk_compras_categorias1`
    FOREIGN KEY (`ref_categorias`)
    REFERENCES `6Bs4988CYl`.`categorias` (`id_categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`utilizadores_has_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`utilizadores_has_compras` (
  `id_utilizadores_has_compras` INT NOT NULL AUTO_INCREMENT,
  `ref_utilizadores` INT NOT NULL,
  `ref_compras` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id_utilizadores_has_compras`),
  INDEX `fk_utilizadores_has_compras_utilizadores1_idx` (`ref_utilizadores` ASC) VISIBLE,
  INDEX `fk_utilizadores_has_compras_compras1_idx` (`ref_compras` ASC) VISIBLE,
  CONSTRAINT `fk_utilizadores_has_compras_utilizadores1`
    FOREIGN KEY (`ref_utilizadores`)
    REFERENCES `6Bs4988CYl`.`utilizadores` (`id_utilizadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilizadores_has_compras_compras1`
    FOREIGN KEY (`ref_compras`)
    REFERENCES `6Bs4988CYl`.`compras` (`id_compras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`favoritos` (
  `ref_utilizadores` INT NOT NULL,
  `ref_compras` INT NOT NULL,
  PRIMARY KEY (`ref_utilizadores`, `ref_compras`),
  INDEX `fk_favoritos_compras1_idx` (`ref_compras` ASC) VISIBLE,
  CONSTRAINT `fk_favoritos_utilizadores1`
    FOREIGN KEY (`ref_utilizadores`)
    REFERENCES `6Bs4988CYl`.`utilizadores` (`id_utilizadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_compras1`
    FOREIGN KEY (`ref_compras`)
    REFERENCES `6Bs4988CYl`.`compras` (`id_compras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`orcamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`orcamentos` (
  `ref_utilizadores` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`ref_utilizadores`),
  INDEX `fk_orcamentos_utilizadores1_idx` (`ref_utilizadores` ASC) VISIBLE,
  CONSTRAINT `fk_orcamentos_utilizadores1`
    FOREIGN KEY (`ref_utilizadores`)
    REFERENCES `6Bs4988CYl`.`utilizadores` (`id_utilizadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `6Bs4988CYl`.`orcamentos_has_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `6Bs4988CYl`.`orcamentos_has_categorias` (
  `id_orcamentos_has_categorias` INT NOT NULL AUTO_INCREMENT,
  `ref_categorias` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `ref_orcamentos` INT NOT NULL,
  PRIMARY KEY (`id_orcamentos_has_categorias`),
  INDEX `fk_orcamentos_has_categorias_categorias1_idx` (`ref_categorias` ASC) VISIBLE,
  INDEX `fk_orcamentos_has_categorias_orcamentos1_idx` (`ref_orcamentos` ASC) VISIBLE,
  CONSTRAINT `fk_orcamentos_has_categorias_categorias1`
    FOREIGN KEY (`ref_categorias`)
    REFERENCES `6Bs4988CYl`.`categorias` (`id_categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orcamentos_has_categorias_orcamentos1`
    FOREIGN KEY (`ref_orcamentos`)
    REFERENCES `6Bs4988CYl`.`orcamentos` (`ref_utilizadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
